disabled_rules:
  - todo
  - implicit_optional_initialization
  - superfluous_disable_command

opt_in_rules:
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - redundant_nil_coalescing
  - sorted_imports
  - toggle_bool
  - untyped_error_in_catch

analyzer_rules:
  - unused_declaration
  - unused_import

# Critical Safety Enforcements
force_try:
  severity: error

force_cast:
  severity: error

identifier_name:
  excluded:
    - id
    - i
    - j
    - r

cyclomatic_complexity:
  warning: 20
  error: 25

function_body_length:
  warning: 70
  error: 100

function_parameter_count:
  warning: 6
  error: 8
  ignores_default_parameters: true

line_length:
  warning: 180
  error: 220

file_length:
  warning: 800
  error: 1200

type_body_length:
  warning: 450
  error: 650

included:
  - MyIIS
  - Shared

excluded:
  - MyIIS/Resources/AppMockData.swift
  - MyIISUITests/SnapshotHelper.swift
